language: python
python:
  - 3.5
  - 3.6
  - pypy3
install:
  - pip install $DJANGO
  - pip install -r test_requirements.txt
env:
  - DJANGO='django>=2,<2.1'
  - DJANGO='django>=2.1,<2.2'
script:
  - flake8
  - coverage run --source=collector run_tests.py
after_success:
  coveralls
